### ISSUE TITLE
compose or pipe ?

### ISSUE THREAD

**Issue by pierreroth64** [arpinum-oss/js-promising#6]
[compose](https://github.com/arpinum-oss/js-promising/blob/master/docs/api.md#composefunctions) applies functions from the _left-to-right_.

What I can see from other popular functional libraries is that `compose` applies functions from _right-to-left_ while `pipe`does it from _left-to-right_:
 - ramdajs: [compose](https://ramdajs.com/docs/#compose) / [pipe](https://ramdajs.com/docs/#pipe)
 - lodash/fp: `_.compose` is an alias of [_.flowRight](https://lodash.com/docs/4.17.15#flowRight) /  `_.pipe` is an alias of [_.flow](https://lodash.com/docs/4.17.15#flow)

I don't know if this is a convention (see [this tutorial](https://egghead.io/lessons/javascript-compose-closures-and-callbacks-to-create-new-functions?pl=introduction-to-callbacks-broadcasters-and-listeners-5bd7)) but I did not understand the `compose` behaviour when first using `@arpinum/promising` package. I think that adding a `pipe` function and changing `compose` to _right-to-left_ would be interesting.

**Comment by MichaelBorde** [comment]
Seems fair.

**Comment by MichaelBorde** [comment]
Fixed by https://github.com/arpinum-oss/js-promising/commit/37751b11bd495d7c3f471551b4bd849278e69d99 and available in `4.0.0`.
